# Generated by Django 4.0.5 on 2022-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('publication_date', models.DateField()),
                ('subject_area', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('cover_photo', models.FilePathField(path='/images')),
            ],
        ),
    ]
